### ISSUE TITLE
시간

### ISSUE THREAD

**Issue by to-kie** [Youngzheimer/pomodoro#1]
열품타가 잘못되거나 이게 잘못되거나 둘중 하난데 열품타가 잘못된거보단 얘가 잘못되었을꺼 같아서
25분으로 설정해놔도 31분 그정도 시간이 지나감

**Comment by Youngzheimer** [comment]
~나도 모르게 공부를 6분이나 더 할 수 있다고?!
이거 완전 럭키비키자낭\~! ☆~

백그라운드에서 타이머 로직이 이상해진것같음
셤끝나고 고칠게요
